name: mood_tracker
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  go_router: ^15.1.2
  intl: ^0.20.2
  carousel_slider: ^5.0.0
  table_calendar: ^3.2.0
  fl_chart: ^1.0.0
  provider: ^6.1.5
  flutter_local_notifications: ^19.2.1
  permission_handler: ^12.0.0+1
  flutter_animate: ^4.5.2
  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  flutter_slidable: ^4.0.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  bloc_lint: ^0.2.0-dev.0
  bloc_test: ^10.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/Angry.png
    - assets/images/Happy.webp
    - assets/images/Sad.webp
    - assets/images/Calm.webp
    - assets/images/Moods.webp